anchor_version = "0.16.1"
gemachain_version = "1.7.11"

[workspace]
members = ["governance/program"]

[provider]
cluster = "mainnet"
wallet = "~/.config/gemachain/id.json"

[programs.mainnet]
gpl_governance = "GoVEr6xcF9QGrRFJC4kt9wiCdNqZzrG7KWdrm7viDnpa"
